name: CI
on: [push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        poetry-version: ["1.4.1"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Setup dependencies
        run: poetry install -E drf -E mercure -E persistance
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: test_settings
        run: poetry run pytest --cov && poetry run coverage xml
